### ISSUE TITLE
versioned kubectl

### ISSUE THREAD

**Issue by wozniakjan** [cisco-sso/ansible-role-k8s-devkit#7]
We would like to upgrade one of the clusters to kubernetes v1.11.x and the vagrant machine currently packs kubectl: 
https://github.com/cisco-sso/ansible-role-k8s-devkit/blob/32127921996dad472dea79409797f69b1c80024b/defaults/main.yml#L133

Theoretically this is within the bounds of supported [version skew](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew) but given the kubectl we use is a _release candidate_, not an actual release, things may not work properly.

Can we pack multiple versions of kubectl and swap between them depending on the kubernetes cluster? Or even better, as @simt2 suggested, we can provide default version of kubectl and lazily pull different release and properly hook it to the system if needed (symlinks maybe).

cc @darkyat @marsavela @simt2

**Comment by josdotso** [comment]
I think the best thing to do here in the short term is bump the default version of kubectl used in the role to latest stable upstream. Other versions if needed can be put in `~/bin` by end user.
